title: Cms Siteleaf
description: Cms Siteleaf is a jekyll theme for GitHub Pages.
logo: /assets/img/logo.png
show_downloads: true
google_analytics:
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
repository: vijay07roy/cms-siteleaf
markdown: kramdown
highlighter: rouge
theme: jekyll-theme-midnight
plugins:
- jekyll-feed
